require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - "bin/**/*"
    - db/schema.rb
    - "node_modules/**/*"
    - "tmp/**/*"
    - 'vendor/bundle/**/*'
  NewCops: enable
  DisplayCopNames: true
  TargetRubyVersion: 3.1

Layout/LineLength:
  Max: 120
  Exclude:
    - config/initializers/devise.rb

Naming/VariableNumber:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Exclude:
    - 'config/environments/production.rb'
    - 'config/environments/development.rb'
    - 'config/routes.rb'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 50

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false
