version: '3'

services:
  mysql:
    image: mysql/mysql-server:8.0.28-1.2.7-server
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - '3306:3306'
  redis:
    image: redis:6.2.6-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_volume:/data
    hostname: redis
  app:
    &app_base
    build: ./docker/app/dev
    command: /bin/sh -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b 0.0.0.0"
    ports:
      - '3000:3000'
    environment:
      PATH: /app/bin:/app/node_modules/.bin:/usr/local/bundle/bin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - .:/app:delegated
      - bundle_volume:/usr/local/bundle
    working_dir: /app
    depends_on:
      - mysql
      - redis
    hostname: app
    privileged: true
    tty: true
    stdin_open: true
  app_js:
    <<: *app_base
    command: yarn build --watch
    ports: []
    hostname: app_js
    tty: false
    stdin_open: false

volumes:
  mysql_volume:
    driver: local
  redis_volume:
    driver: local
  bundle_volume:
    driver: local
